- .husky/commit-msg
- commitlint.config.js
- package-lock.json
- package.json
> Integrate commitlint

- src/parsing/index.ts
> feat: specify type for ParseResult.suggestAggregateFunctions

- src/parsing/test/testing.ts
Closes #38 
PR has the prefix `feat`, because we want a release. Actually it should be `refactor`
> feat: refactor test case message construction

- src/parsing/index.ts
Part of https://github.com/gravity-ui/websql/issues/353
> feat: expand suggestTables interface

- src/parsing/index.ts
> feat: specify locations in ParseResult

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> feat!: rename sql-autocomplete-parsers to websql-autocomplete

- .github/workflows/release.yml
> ci: bump release action node version to 18

- package-lock.json
- package.json
> fix: package name

- src/autocomplete/postgresql/grammar/PostgreSqlParser.g4
- src/autocomplete/postgresql/grammar/PostgreSqlParserBase.ts
- src/tests/postgresql/create/create-function.test.ts
> fix: broken psql super class throwing errors on function creation

- package-lock.json
- package.json
> ci: change library name to @gravity-ui/websql-autocomplete

- package-lock.json
- package.json
- src/autocomplete/databases/clickhouse/clickhouse-autocomplete.ts
- src/autocomplete/databases/clickhouse/generated/ClickHouseParser.ts
- src/autocomplete/databases/clickhouse/tests/select/join-clause.test.ts
- src/autocomplete/databases/mysql/generated/MySqlParser.ts
- src/autocomplete/databases/mysql/mysql-autocomplete.ts
- src/autocomplete/databases/mysql/tests/select/join-clause.test.ts
- src/autocomplete/databases/postgresql/generated/PostgreSqlLexer.ts
- src/autocomplete/databases/postgresql/grammar/PostgreSqlParserBase.ts
- src/autocomplete/databases/postgresql/postgresql-autocomplete.ts
- src/autocomplete/databases/postgresql/tests/select/join-clause.test.ts
- src/autocomplete/databases/yql/generated/YQLParser.ts
- src/autocomplete/databases/yql/tests/yql/select/join-clause.test.ts
- src/autocomplete/databases/yql/tests/yql/select/where-clause.test.ts
- src/autocomplete/databases/yql/yql-autocomplete.ts
- src/autocomplete/shared/cursor.test.ts
- src/autocomplete/shared/query.ts
- src/autocomplete/shared/symbol-table.ts
> feat: suggest multiple tables with same name and different aliases

- package-lock.json
- package.json
> chore: update antlr-format-cli

- src/autocomplete/autocomplete-types.ts
- src/autocomplete/databases/yql/helpers.ts
- src/autocomplete/databases/yql/tests/yql/create/create-external.test.ts
- src/autocomplete/databases/yql/tests/yql/create/create-replication.test.ts
- src/autocomplete/databases/yql/tests/yql/create/create-table.test.ts
- src/autocomplete/databases/yql/tests/yql/create/create-topic.test.ts
- src/autocomplete/databases/yql/types.ts
> fix(YQL): suggest entity settings as YQLEntity

- src/autocomplete/databases/yql/helpers.ts
- src/autocomplete/databases/yql/tests/yq/select/group-by-clause.test.ts
- src/autocomplete/databases/yql/tests/yq/select/join-clause.test.ts
- src/autocomplete/databases/yql/tests/yq/select/order-by-clause.test.ts
- src/autocomplete/databases/yql/tests/yq/select/select.test.ts
- src/autocomplete/databases/yql/tests/yq/select/where-clause.test.ts
- src/autocomplete/databases/yql/tests/yql/create/create-user.test.ts
- src/autocomplete/databases/yql/tests/yql/select/group-by-clause.test.ts
- src/autocomplete/databases/yql/tests/yql/select/join-clause.test.ts
- src/autocomplete/databases/yql/tests/yql/select/order-by-clause.test.ts
- src/autocomplete/databases/yql/tests/yql/select/select.test.ts
- src/autocomplete/databases/yql/tests/yql/select/where-clause.test.ts
> feat(YQL): suggest simple types in expressions

- README.md
> chore: fix npm package badge

- src/autocomplete/databases/clickhouse/index.ts
- src/autocomplete/databases/mysql/index.ts
- src/autocomplete/databases/postgresql/index.ts
- src/autocomplete/databases/redis/index.ts
- src/autocomplete/databases/redis/redis-autocomplete.ts
- src/autocomplete/databases/redis/tests/commands/commands.test.ts
- src/autocomplete/databases/redis/tests/decrement/decrement.test.ts
- src/autocomplete/databases/redis/tests/get/get.test.ts
- src/autocomplete/databases/redis/tests/increment/increment.test.ts
- src/autocomplete/databases/redis/tests/set/set.test.ts
- src/autocomplete/databases/yql/types.ts
- src/autocomplete/shared/autocomplete-types.ts
- src/autocomplete/shared/parse-query-with-cursor.test.ts
- src/autocomplete/shared/parse-query-with-cursor.ts
- src/autocomplete/shared/tables.ts
> feat: add Redis autocomplete

- src/autocomplete/databases/redis/index.ts
- src/autocomplete/databases/redis/redis-tokenize.ts
- src/autocomplete/databases/redis/tests/tokenize/tokenize.test.ts
- src/autocomplete/databases/yql/index.ts
- src/autocomplete/shared/tokenize.ts
> feat: add ability to extract redis commands from query

- build.js
- package.json
> fix: export shared types

- build.js
- package.json
> feat: support cjs build

- src/autocomplete/databases/yql/helpers.ts
- src/autocomplete/databases/yql/tests/yq/insert/insert.test.ts
- src/autocomplete/databases/yql/tests/yq/select/nested-statements.test.ts
- src/autocomplete/databases/yql/tests/yq/select/select.test.ts
- src/autocomplete/databases/yql/tests/yql/insert/insert.test.ts
- src/autocomplete/databases/yql/tests/yql/select/nested-statements.test.ts
- src/autocomplete/databases/yql/tests/yql/select/select.test.ts
- src/autocomplete/databases/yql/tests/yql/upsert/upsert.test.ts
- src/autocomplete/databases/yql/types.ts
- src/autocomplete/databases/yql/yql-autocomplete.ts
- src/autocomplete/shared/autocomplete-types.ts
- src/autocomplete/shared/tables.ts
> feat(YQL): support UPSERT and all columns suggestions

- src/autocomplete/databases/yql/index.ts
> fix(YQL): explicitely export types

- package.json
> fix(package.json): improve exports section
